# Generated by Django 4.0.4 on 2022-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 25,00, o valor padrão é 0 ', max_digits=20, verbose_name='Valor')),
                ('horarario_abre_segunda', models.TimeField(blank=True, null=True, verbose_name='Horário abre segunda')),
                ('horarario_fecha_segunda', models.TimeField(blank=True, null=True, verbose_name='Horário abre segunda')),
                ('horarario_abre_terca', models.TimeField(blank=True, null=True, verbose_name='Horário abre terça')),
                ('horarario_fecha_terca', models.TimeField(blank=True, null=True, verbose_name='Horário fecha terça')),
                ('horarario_fecha_quarta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha quarta')),
                ('horarario_abre_quinta', models.TimeField(blank=True, null=True, verbose_name='Horário abre quinta')),
                ('horarario_fecha_quinta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha quinta')),
                ('horarario_abre_sexta', models.TimeField(blank=True, null=True, verbose_name='Horário abre sexta')),
                ('horarario_fecha_sexta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha sexta')),
                ('horarario_abre_sabado', models.TimeField(blank=True, null=True, verbose_name='Horário abre sábado')),
                ('horarario_fecha_sabado', models.TimeField(blank=True, null=True, verbose_name='Horário fecha sábado')),
                ('horarario_abre_domingo', models.TimeField(blank=True, null=True, verbose_name='Horário fecha domingo')),
                ('horarario_fecha_domingo', models.TimeField(blank=True, null=True, verbose_name='Horário fecha domingo')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('dia_inicio', models.DateField(verbose_name='Dia Início')),
                ('dia_final', models.DateField(blank=True, null=True)),
                ('horario_inicial', models.TimeField()),
                ('horario_termina', models.TimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=300, verbose_name='Site do Evento')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 25.00', max_digits=20, null=True, verbose_name='Valor')),
                ('descricao', models.TextField(max_length=1000, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('url', models.URLField(verbose_name='Site')),
                ('telefone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('url', models.URLField(max_length=300, verbose_name='Site')),
                ('telefone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('horarario_abre_segunda', models.TimeField(blank=True, null=True, verbose_name='Horário abre segunda')),
                ('horarario_fecha_segunda', models.TimeField(blank=True, null=True, verbose_name='Horário abre segunda')),
                ('horarario_abre_terca', models.TimeField(blank=True, null=True, verbose_name='Horário abre terça')),
                ('horarario_fecha_terca', models.TimeField(blank=True, null=True, verbose_name='Horário fecha terça')),
                ('horarario_fecha_quarta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha quarta')),
                ('horarario_abre_quinta', models.TimeField(blank=True, null=True, verbose_name='Horário abre quinta')),
                ('horarario_fecha_quinta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha quinta')),
                ('horarario_abre_sexta', models.TimeField(blank=True, null=True, verbose_name='Horário abre sexta')),
                ('horarario_fecha_sexta', models.TimeField(blank=True, null=True, verbose_name='Horário fecha sexta')),
                ('horarario_abre_sabado', models.TimeField(blank=True, null=True, verbose_name='Horário abre sábado')),
                ('horarario_fecha_sabado', models.TimeField(blank=True, null=True, verbose_name='Horário fecha sábado')),
                ('horarario_abre_domingo', models.TimeField(blank=True, null=True, verbose_name='Horário fecha domingo')),
                ('horarario_fecha_domingo', models.TimeField(blank=True, null=True, verbose_name='Horário fecha domingo')),
            ],
        ),
    ]
