# Generated by Django 4.0.4 on 2022-05-20 22:02

from django.db import migrations, models
import turismo.models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_remove_restaurante_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=turismo.models.upload_image_restaurante),
        ),
    ]
