# Generated by Django 4.0.4 on 2022-05-20 22:08

from django.db import migrations, models
import turismo.models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_restaurante_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrativo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=turismo.models.upload_image_atrativo),
        ),
        migrations.AddField(
            model_name='evento',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=turismo.models.upload_image_evento),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=turismo.models.upload_image_hotel),
        ),
    ]
